feature_name: Application Password
feature_description: |
  See [[https://documentation.open-xchange.com/{{version}}/middleware/login_and_sessions/application_passwords.html]] for more information.
properties:
    - key: com.openexchange.authentication.application.enabled
      description: |
        Configures whether application-specific passwords are globally enabled or not.
      defaultValue: false
      version: 7.10.4
      reloadable: false
      configcascadeAware: false
      related: 
      file: appPasswords.properties
      packageName: open-xchange-core
      tags: ["Authentication", "AppPasswords"]

    - key: com.openexchange.authentication.application.blacklistedClients
      description: |
        Defines client strings that identify appsuite UI or clients that should not
        be allowed to use application passwords.  Comma separated list
      defaultValue: "open-xchange-appsuite,com.openexchange.ajax.framework.AJAXClient"
      version: 7.10.4
      reloadable: true
      configcascadeAware: false
      related: 
      file: appPasswords.properties
      packageName: open-xchange-core
      tags: ["Authentication", "AppPasswords"]

    - key: com.openexchange.authentication.application.appTypes
      description: |
        Comma separated list of defined application types that should be available for a user, e.g. 
        "mailapp,caldav,carddav,driveapp,webdav". Each type listed here needs to be defined through appPasswordApps.yaml.  
      defaultValue: ""
      version: 7.10.4
      reloadable: true
      configcascadeAware: true
      related: 
      file: appPasswords.properties
      packageName: open-xchange-core
      tags: ["Authentication", "AppPasswords"]

    - key: com.openexchange.authentication.application.storage.rdb.enabled
      description: |
        Configures whether the database-backed application password storage is generally enabled or not.
      defaultValue: true
      version: 7.10.4
      reloadable: false
      configcascadeAware: false
      file: appPasswords.properties
      packageName: open-xchange-authentication-application-storage-rdb
      tags: ["Authentication", "AppPasswords"]

    - key: com.openexchange.authentication.application.storage.rdb.contextLookupNamePart
      description: |
        Defines the name part of the context lookup source value used for determining the context of a user. Possible values are
        
        full - The full string of the value
        local-part - The local part of an email address (local-part@domain),
                     if the provided name matches such. In case the name does not match
                     an email address, the full string is taken.
        domain - The domain part of an email address (local-part@domain),
                 if the provided name matches such. In case the name does not match
                 an email address, "defaultcontext" is taken.
      defaultValue: domain
      version: 7.10.4
      reloadable: true
      configcascadeAware: false
      file: appPasswords.properties
      packageName: open-xchange-authentication-application-storage-rdb
      tags: ["Authentication", "AppPasswords"]

    - key: com.openexchange.authentication.application.storage.rdb.storeUserPassword
      description: |
        When enabled, encrypts and stores the user's regular session password in the application password authentication. Required if
        applications accessing external systems like the mail server need their individual credentials rather than master- or OAuth-based
        authentication.
      defaultValue: false
      version: 7.10.4
      reloadable: true
      configcascadeAware: true
      file: appPasswords.properties
      packageName: open-xchange-authentication-application-storage-rdb
      tags: ["Authentication", "AppPasswords"]

    - key: com.openexchange.authentication.application.storage.rdb.loginNameSource
      description: |
        Configures where the login name used for application credentials is taken from. Possible options are 'session' to use
        the login information from the actual regular session as-is, 'mail' to take over the user's primary mail address,
        'username' to use the user's name, or 'synthetic' to construct the name from the stored login mappings
        associated with the user and context, separated by the '@'-character.
        Defaults to 'session'.
      defaultValue: session
      version: 7.10.4
      reloadable: true
      configcascadeAware: true
      file: appPasswords.properties
      packageName: open-xchange-authentication-application-storage-rdb
      tags: ["Authentication", "AppPasswords"]
