{{- if .Values.enabled.appsuiteSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "core-mw.appsuiteSecret" . }}
type: Opaque
data:
  master-admin: {{ required "masterAdmin value missing" .Values.masterAdmin }}
  master-pw: {{ required "masterPassword value missing" .Values.masterPassword }}
  hz-group-name: {{ required "hzGroupName value missing" .Values.hzGroupName }}
  hz-group-pw: {{ required "hzGroupPassword value missing" .Values.hzGroupPassword }}
  basic-auth-login: {{ required "basicAuthLogin value missing" .Values.basicAuthLogin }}
  basic-auth-password: {{ required "basicAuthPassword value missing" .Values.basicAuthPassword }}
  jolokia-login: {{ required "jolokiaLogin value missing" .Values.jolokiaLogin }}
  jolokia-password: {{ required "jolokiaPassword value missing" .Values.jolokiaPassword }}
  credstorage-passcrypt: {{ required "credstoragePasscrypt value missing" .Values.credstoragePasscrypt }}
  doveadm-api-key: {{ required "doveAdmAPIKey is missing" .Values.doveAdmAPIKey }}
{{- end -}}