apiVersion: v1
kind: Service
metadata:
  name: {{ include "core-mw.fullname" . }}
  labels:
    {{- include "core-mw.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "core-mw.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "core-mw.fullname" . }}-hazelcast
  labels:
    {{- include "core-mw.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    {{- include "core-mw.selectorLabels" . | nindent 4 }}
  ports:
    - name: hazelcast 
      port: 5701
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
